**Задача 1**

Переменная **car_speed** хранит скорость движения автомобиля. 

Переменная **speed_limit** — разрешённую скорость на текущем участке дороги.


Напишите программу, которая снизит скорость автомобиля до разрешённой в случае превышения.

In [19]:
from random import randint

car_speed = 80
speed_limit = 60

print('Скорость автомобиля:', car_speed)
print('Разрешённая скорость:', speed_limit)

while car_speed > speed_limit:
    car_speed -= randint(1, 60)

print()
print('Скорость автомобиля:', car_speed)
print('Разрешённая скорость:', speed_limit)

Скорость автомобиля: 80
Разрешённая скорость: 60

Скорость автомобиля: 46
Разрешённая скорость: 60

**Задание 2**

Сделайте Зверей добрыми. Выведите на экран все значения списка **dangerous_animals**, предваряя каждый элемент словом 'добрый'.

In [59]:
dangerous_animals = ['волк', 'медведь', 'тигр', 'крокодил', 'леопард', 'бегемот', 'удав', 'тираннозавр', 'лев']

for animals in dangerous_animals:
    animals = 'добрый ' + str(animals)
    print(animals)

добрый волк
добрый медведь
добрый тигр
добрый крокодил
добрый леопард
добрый бегемот
добрый удав
добрый тираннозавр
добрый лев

**Задание 3**


Список **july_temperatures** хранит дневные значения температуры в цельсиях за июль.

Сделайте лето теплее — напишите цикл, который добавит по 10 градусов к каждому значению. 

Выведите изменённый список на экран.

In [71]:
july_temperatures = [15, 17, 17, 13, 8, 12, 12, 12, 9, 15, 8, 10, 11, 9, 13, 9, 8, 
                     11, 9, 16, 7, 12, 14, 10, 7, 16, 13, 12, 7, 12, 15]

for i in range(len(july_temperatures)):
    july_temperatures[i] = (july_temperatures[i]+10) 
    
print(july_temperatures)

[25, 27, 27, 23, 18, 22, 22, 22, 19, 25, 18, 20, 21, 19, 23, 19, 18, 21, 19, 26, 17, 22, 24, 20, 17, 26, 23, 22, 17, 22, 25]

**Задание 4**

Список **payers** хранит количество пользователей, которые купили платную версию приложения в каждом месяце прошлого года. 

Цена приложения записана в переменной **purchase_amount** — 5.

Напишите цикл, который посчитает и выведет на экран заработок от продаж приложения за каждый месяц.

In [23]:
payers = [75, 48, 65, 68, 74, 67, 71, 65, 90, 85, 79, 81]
purchase_amount = 5  # сумма покупки 

total = 0

for i in payers:
    total = purchase_amount*i
    print(f'заработок от продаж за каждый месяц: {total}')

заработок от продаж за каждый месяц: 375
заработок от продаж за каждый месяц: 240
заработок от продаж за каждый месяц: 325
заработок от продаж за каждый месяц: 340
заработок от продаж за каждый месяц: 370
заработок от продаж за каждый месяц: 335
заработок от продаж за каждый месяц: 355
заработок от продаж за каждый месяц: 325
заработок от продаж за каждый месяц: 450
заработок от продаж за каждый месяц: 425
заработок от продаж за каждый месяц: 395
заработок от продаж за каждый месяц: 405

**Задание 5**

В предыдущем задании вы написали цикл, который вывел на экран заработок от продаж платной версии приложения за каждый месяц. 

Теперь напишите цикл, который сохранит эти данные в отдельный список — **monthly_income**.

In [12]:
payers = [75, 48, 65, 68, 74, 67, 71, 65, 90, 85, 79, 81]
purchase_amount = 5  # сумма покупки

# создайте список monthly_income
monthly_income = []

# напишите цикл, который заполнит monthly_income значениями
for i in payers:
    total = purchase_amount*i
    monthly_income.append(total)


print(monthly_income) # выводим новый список на экран

[375, 240, 325, 340, 370, 335, 355, 325, 450, 425, 395, 405]

**Задание 6**

Рассчитайте конверсию — разделите каждый элемент списка **payers** на соответствующий элемент списка **installs** и выведите результат на экран.

In [22]:
installs = [5018, 4312, 4208, 3665, 3957, 4912, 5074, 5165, 4704, 4447, 4189, 4371]
payers = [75, 48, 65, 68, 74, 67, 71, 65, 90, 85, 79, 81]


for i, j in zip(payers,installs):
    total = i/j
    print(f'конверсия: {total}')

конверсия: 0.014946193702670387
конверсия: 0.011131725417439703
конверсия: 0.015446768060836502
конверсия: 0.018553888130968622
конверсия: 0.018701036138488752
конверсия: 0.013640065146579805
конверсия: 0.013992905005912494
конверсия: 0.012584704743465635
конверсия: 0.01913265306122449
конверсия: 0.019114009444569372
конверсия: 0.01885891620911912
конверсия: 0.018531228551818806

**Задание 7**

Рассчитайте конверсию по месяцам, но на этот раз сохраните результат в отдельном списке — **conversions**

In [25]:
installs = [5018, 4312, 4208, 3665, 3957, 4912, 5074, 5165, 4704, 4447, 4189, 4371]
payers = [75, 48, 65, 68, 74, 67, 71, 65, 90, 85, 79, 81]

conversions = []

for i, j in zip(payers,installs):
    total = i/j
    conversions.append(total)

print(conversions)

[0.014946193702670387, 0.011131725417439703, 0.015446768060836502, 0.018553888130968622, 0.018701036138488752, 0.013640065146579805, 0.013992905005912494, 0.012584704743465635, 0.01913265306122449, 0.019114009444569372, 0.01885891620911912, 0.018531228551818806]

**Задание 8**

Узнайте, сколько всего денег заработали на покупках приложения пользователями. 

Посчитайте доходы за каждый месяц и сохраните полученные значения в отдельный список, а затем сложите их и выведите результат на экран.

In [29]:
payers = [75, 48, 65, 68, 74, 67, 71, 65, 90, 85, 79, 81, 87, 61, 73, 77, 76, 70, 79, 61, 63, 67, 89, 65, 73, 
          71, 78, 73, 61, 85, 62, 86, 80, 79, 68, 76, 87, 85, 71, 65, 75, 70, 61, 83, 65, 86, 61, 71]
purchase_amount = 5

monthly_income = []

for i in payers:
    total = purchase_amount*i
    monthly_income.append(total)

total_sum = sum(monthly_income)
print(total_sum)

17540

**Задание 9**

Напечатайте сообщение 'Основы аналитики данных' 50 раз с помощью циклов

In [33]:
for i in range(50): 
    print('Основы аналитики данных')

Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных
Основы аналитики данных

**Задание 10**

Посчитайте суммарную продолжительность всех фильмов в таблице.

In [39]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

total=0

for row in movies_table:
    total += row[4]
        
print(total)

1768

**Задание 11**

В конец каждого вложенного списка добавьте тип фильма: 'полнометражный'

In [46]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

for row in movies_table:
    row.append('полнометражный')
    print(row)

['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111, 'полнометражный']
['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.73, 'полнометражный']
['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499, 'полнометражный']
['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818, 'полнометражный']
['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625, 'полнометражный']
['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619, 'полнометражный']
['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521, 'полнометражный']
['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644, 'полнометражный']
['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106, 'полнометражный']
['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083, 'полнометражный']
['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094, 'полнометражный']

**Задание 12**

В таблице movies_table последние два значения - рейтинги на разных платформах. 

Найдите средний рейтинг и добавьте информацию в таблицу

In [73]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111, 9.3],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730, 9.2],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499, 8.9],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818, 8.9],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625, 8.9],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619, 8.9],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521, 8.8],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644, 8.8],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106, 8.7],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083, 8.2],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094, 8.3]
]


total = 0

for row in movies_table:
    total = row[5]+row[6]
    average = total/2
    row.append(average)
    
for row in movies_table: 
    print(row)

['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111, 9.3, 9.2055]
['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.73, 9.2, 8.965]
['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499, 8.9, 8.6995]
['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818, 8.9, 8.859]
['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625, 8.9, 8.7625]
['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619, 8.9, 8.7595]
['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521, 8.8, 8.6605]
['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644, 8.8, 8.722000000000001]
['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106, 8.7, 8.402999999999999]
['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083, 8.2, 8.1415]
['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094, 8.3, 8.197]

**Задание 13**

Создайте фильтр, который сохранит в новую таблицу только те фильмы, что длятся больше 180 минут:

In [72]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

movies_table_filter = [] 

for row in movies_table: 
    if row[4] > 180: 
        movies_table_filter.append(row) 
        

for row_filter in movies_table_filter: 
    print(row_filter)

['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818]
['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625]