**Задание 1**

С помощью цикла for переберите и выведите на экран элементы списка **group_name** каждый с новой строки

In [15]:
group_name = [8115, 8124, 6027, 6028, 8011, 8028, 8031, 6927, 8911, 8914, 8916, 8917, 8918, 8924,
             8928, 8931, 8933, 8934, 8935, 8936, 8938, 8816, 8817, 8833, 8838, 8839]

for group_name in group_name:
    print('Имя группы', group_name)

Имя группы 8115
Имя группы 8124
Имя группы 6027
Имя группы 6028
Имя группы 8011
Имя группы 8028
Имя группы 8031
Имя группы 6927
Имя группы 8911
Имя группы 8914
Имя группы 8916
Имя группы 8917
Имя группы 8918
Имя группы 8924
Имя группы 8928
Имя группы 8931
Имя группы 8933
Имя группы 8934
Имя группы 8935
Имя группы 8936
Имя группы 8938
Имя группы 8816
Имя группы 8817
Имя группы 8833
Имя группы 8838
Имя группы 8839

**Вопросы по 1 заданию**

**Задание 2**

В списке **less_duration** указано продолжительность нескольких предметов в часах. 

Прибавьте 2 часа к каждому элементу списка.

In [16]:
less_duration = [34, 51, 68, 20, 10]

for i in range(len(less_duration)):
    less_duration[i] = (less_duration[i]+2)

print(less_duration)

[36, 53, 70, 22, 12]

**Вопросы по 2 заданию**

**Задание 3**

Список **less_duration** хранит продолжительность предметов в часах. 

Создайте цикл **for**, который найдёт суммарное количество часов. 

Объявите переменную **total** для накопления часов. 

После завершения работы цикла выведите результат на экран.

In [18]:
less_duration = [34, 51, 68, 20, 10]

total = 0
for duration in less_duration:
    total += duration

print(total)

183

**Вопросы по 3 заданию**

**Задание 4**

Найдите суммарное количество часов с помощью встроенной функции sum() и сохраните его в переменную total.

In [19]:
less_duration = [34, 51, 68, 20, 10]

total = sum(less_duration)

print(total)

183

**Вопросы по 4 заданию**

**Задание 5**

Обратитесь к списку movies_table и выведите на экран:

- страну производства фильма «Сталкер»

- год выхода фильма «Криминальное чтиво»

- рейтинг фильма «Крёстный отец»

Извлекайте элементы по индексу и выводите их функцией print(), каждый элемент на новой строке.

In [20]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

print(movies_table[9][1])
print(movies_table[5][2])
print(movies_table[1][5])

СССР
1994
8.73

**Вопросы по 5 заданию**

**Задание 6**

Выведите на экран столбец с жанрами фильмов таблицы movies_table. Каждое значение выводите на новой строке.

In [116]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

for row in movies_table:
    print(row[3])

драма
драма, криминал
фантастика, боевик, триллер
драма
фэнтези, приключения, драма
триллер, комедия, криминал
вестерн
триллер, драма, криминал
драма, боевик, история
фантастика, драма, детектив
драма, военный

**Вопросы по 6 заданию**

**Задание 7**

Выведите на экран столбец с годом релиза из таблицы movies_table. Каждое значение выводите на новой строке.

In [4]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

for row in movies_table:
    print(row[2])

1994
1972
2008
1993
2003
1994
1966
1999
1962
1979
1985

**Вопросы по 7 заданию**

**Задание 8**

В списке списков sales_info хранится число продаж пяти филиалов компании. С помощью цикла посчитайте сумму продаж всех филиалов.

Результат сохраните в переменную total. Тогда функция print() выведет его на экран.

In [154]:
# [название филиала, количество продаж]
sales_info = [
    ['центральный', 15000],
    ['западный', 9000],
    ['восточный', 2000],
    ['южный', 11000],
    ['северный', 4500]
]

total = 0

for row in sales_info:
    total += row[1]
   
        
print(total)

41500

**Вопросы по 8 заданию**

**Задание 9**

В списке списков movies_table найдите сумму всех значений рейтинга.

In [158]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

rating_total = 0

for row in movies_table:
    rating_total += row[5]

print(rating_total)

93.85

**Вопросы по 9 заданию**

**Задание 10**

В конец каждого вложенного списка добавьте Фамилию одного студента

In [12]:
digital_kaf = [
    [8115],
    [8124],
    [6027],
    [6028],
    [8011],
    [8028],
    [8031],
    [6927],
    [8911],
    [8914],
    [8916],
    [8917],
    [8918],
    [8924],
    [8928],
    [8931],
    [8934],
    [8935],
    [8936],
    [8938],
    [8816],
    [8817],
    [8833],
    [8838],
    [8839]
]

for row in digital_kaf:
    row.append('Петров')

for row in digital_kaf: 
    for elem in row: 
        print(elem, end='   ') 
    print()

8115   Петров
8124   Петров
6027   Петров
6028   Петров
8011   Петров
8028   Петров
8031   Петров
6927   Петров
8911   Петров
8914   Петров
8916   Петров
8917   Петров
8918   Петров
8924   Петров
8928   Петров
8931   Петров
8934   Петров
8935   Петров
8936   Петров
8938   Петров
8816   Петров
8817   Петров
8833   Петров
8838   Петров
8839   Петров

**Вопросы по 10 заданию**

**Задание 11**

В каждой строке таблицы — данные о выручке магазинов в разных регионах:

- элемент с индексом 1 — выручка за первое полугодие

- с индексом 2 — за второе

Добавьте в конец каждого вложенного списка сумму продаж за год.

In [63]:
sales = [
    ['Московская область', 105820, 112180],
    ['Ленинградская область', 85899, 91021],
    ['Самарская область', 35010, 32001],
    ['Ростовская область', 37011, 39595]
]

sales_total = 0

for row in sales:
    sales_total = row[1]+row[2]
    row.append(sales_total)

for row in sales:
    print(row)
print()


#или можно так? но тогда не очень красиво выходит 
print(sales)

['Московская область', 105820, 112180, 218000]
['Ленинградская область', 85899, 91021, 176920]
['Самарская область', 35010, 32001, 67011]
['Ростовская область', 37011, 39595, 76606]

[['Московская область', 105820, 112180, 218000], ['Ленинградская область', 85899, 91021, 176920], ['Самарская область', 35010, 32001, 67011], ['Ростовская область', 37011, 39595, 76606]]

**Вопросы по 11 заданию**

**Задание 12**

С помощью условного оператора проверьте количество студентов в группе». Если количество студентов больше или равно 18, выведите на экран сообщение **'Многочисленная группа'**, иначе — **'Малочисленная группа'**.

In [64]:
group_count = 18 

if group_count >= 18:
    print('Многочисленная группа')

else:
    print('Малочисленная группа')

Многочисленная группа

**Вопросы по 12 заданию**

**Задание 13**

Проверьте группу 8833:

- если в данной группу количество студентов больше или равно 18 , выведите на экран **Да**

- Если меньше - **Нет**

Для этого вызовите условный оператор и обратитесь к нужному элементу списка по индексу.

In [59]:
digital_kaf = [
    [8115, 'Александрова', 'Баданова', 'Боднар', 10],
    [8839, 'Агабегян', 'Белов', 'Богданов', 15],
    [8124, 'Дитятев', 'Иванов', 'Масликов', 3],
    [8838, 'Анцыгин', 'Бондаренко', 'Вахитова', 16],
    [6027, 'Агабекян', 'Васильева', 'Зайцева', 15],
    [8833, 'Арефьева', 'Аржакова', 'Берчук', 22],
    [6028, 'Бирюкова', 'Грищук', 'Карташев', 14],
    [8817, 'Алмакаев', 'Бады', 'Гавриш', 13],
    [8011, 'Алиев', 'Бобров', 'Виленский', 18],
    [8816, 'Акулич', 'Антонова', 'Багренина', 18],
    [8028, 'Андреева', 'Бондаренко', 'Бородич', 15]
]

if digital_kaf[5][4] >= 18:
    print('Да')
    
else:
    print('Нет')

Да

**Вопросы по 13 заданию**

**Задание 14**

Переменная marks хранит оценки фильмов. С помощью цикла и условного оператора переведите оценки из стобалльной системы в пятибалльную по этим правилам:

- оценка 2: от 0 до 59 баллов;
- оценка 3: от 60 до 72 баллов;
- оценка 4: от 73 до 84 баллов;
- оценка 5: от 85 до 100 баллов.

По мере прохождения по списку печатайте результаты на экране. Каждую оценку выводите на новой строке.

In [195]:
marks = [91, 35, 65, 89, 78, 93]

for mark in marks:
    if mark >= 0 and mark <= 59:
        print('оценка 2')
    elif mark >= 60 and mark <= 72:
        print('оценка 3')
    elif mark >= 73 and mark <= 84:
        print('оценка 4')
    elif mark >= 85 and mark <= 100:
        print('оценка 5')
    else:
        print('оценка не определена')

оценка 5
оценка 2
оценка 3
оценка 5
оценка 4
оценка 5

**Вопросы по 14 заданию**

**Задание 15**



Перед вами список со странами выхода некоторых фильмов. Для каждого элемента напечатайте сообщение в зависимости от названия страны:

- для СССР напечатайте 'Фильм вышел в СССР.'

- для США — 'The movie was released in USA.'

- для Италии — 'Il film e stato rilasciato in Italia.'

- для любой другой страны — 'Страна не определена.'.


Каждое сообщение выводите на новой строке.

In [65]:
countries = ['СССР', 'Новая Зеландия', 'Италия', 'Италия', 'СССР', 'США']

for country in countries:
    if country == 'СССР':
        print('Фильм вышел в СССР')
    elif country == 'США':
        print('The movie was released in USA.')
    elif country == 'Италия':
        print('Il film e stato rilasciato in Italia.')
    else:
        print('Страна не определена.')

Фильм вышел в СССР
Страна не определена.
Il film e stato rilasciato in Italia.
Il film e stato rilasciato in Italia.
Фильм вышел в СССР
The movie was released in USA.

**Вопросы по 15 заданию**

**Задание 16**

С помощью фильтра извлеките из  таблицы digital_kaf, группы численностью 15 человек. 

Результат сохраните в group_filtered и выведет результат на экран.

In [85]:
digital_kaf = [
    [8115, 'Александрова', 'Баданова', 'Боднар', 10],
    [8839, 'Агабегян', 'Белов', 'Богданов', 15],
    [8124, 'Дитятев', 'Иванов', 'Масликов', 3],
    [8838, 'Анцыгин', 'Бондаренко', 'Вахитова', 16],
    [6027, 'Агабекян', 'Васильева', 'Зайцева', 15],
    [8833, 'Арефьева', 'Аржакова', 'Берчук', 22],
    [6028, 'Бирюкова', 'Грищук', 'Карташев', 14],
    [8817, 'Алмакаев', 'Бады', 'Гавриш', 13],
    [8011, 'Алиев', 'Бобров', 'Виленский', 18],
    [8816, 'Акулич', 'Антонова', 'Багренина', 18],
    [8028, 'Андреева', 'Бондаренко', 'Бородич', 15]
]

digital_kaf_filter = []

for row in digital_kaf: 
    if row[4] == 15:
        digital_kaf_filter.append(row)
        
for group_filtered in digital_kaf_filter:
    print(group_filtered[0])

8839
6027
8028

**Вопросы по 16 заданию**

есть ли разница если индекс [0] убрать из print(group_filtered[0]), и добавить его в digital_kaf_filter.append(row[0]) ? 

Результат выходит тот же. Но ведь получается внутрь списка digital_kaf_filter сохраняется только список групп, без фамилий и количества человек, а как лучше и правильнее? 

Или надо было выводить вовсе не группы, а полностью 3 списка (группы, включая фамилии и численность)?

**Задание 17**

С помощью фильтра извлеките из  таблицы digital_kaf, группы численностью 18 и более человек. 

Результат сохраните в group_filtered и выведет результат на экран.

In [88]:
digital_kaf = [
    [8115, 'Александрова', 'Баданова', 'Боднар', 10],
    [8839, 'Агабегян', 'Белов', 'Богданов', 15],
    [8124, 'Дитятев', 'Иванов', 'Масликов', 3],
    [8838, 'Анцыгин', 'Бондаренко', 'Вахитова', 16],
    [6027, 'Агабекян', 'Васильева', 'Зайцева', 15],
    [8833, 'Арефьева', 'Аржакова', 'Берчук', 22],
    [6028, 'Бирюкова', 'Грищук', 'Карташев', 14],
    [8817, 'Алмакаев', 'Бады', 'Гавриш', 13],
    [8011, 'Алиев', 'Бобров', 'Виленский', 18],
    [8816, 'Акулич', 'Антонова', 'Багренина', 18],
    [8028, 'Андреева', 'Бондаренко', 'Бородич', 15]
]


digital_kaf_filter = []

for row in digital_kaf: 
    if row[4] >= 18:
        digital_kaf_filter.append(row)
        
for group_filtered in digital_kaf_filter:
    print(group_filtered[0])

8833
8011
8816

**Вопросы по 17 заданию**

Тут такой же вопрос что и в 16 задании

**Задание 18**

Оставьте в списке списков movies_filtered информацию только о тех фильмах таблицы movies_table, которые вышли в США и имеют хронометраж более 150 минут.

In [94]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

movies_filtered = []

for row in movies_table:
    if row[1] == 'США' and row[4] > 150:
        movies_filtered.append(row)

for movies in movies_filtered:
    print(movies)

['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.73]
['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499]
['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818]
['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619]

**Вопросы по 18 заданию**

**Задание 19**

Сохраните в movies_filtered информацию только о тех фильмах таблицы, которые либо вышли в 1994 году, либо имеют рейтинг ниже 8.5.

In [95]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

movies_filtered = []

for row in movies_table:
    if row[2] == 1994 or row[5] < 8.5:
        movies_filtered.append(row)

for movies in movies_filtered:
    print(movies)

['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111]
['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499]
['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619]
['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106]
['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083]
['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]

**Вопросы по 19 заданию**

**Задание 20**

Посчитайте триллеры в movies_table. Результат сохраните в thrillers_count — тогда функция выведет его на экран.

In [152]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

thrillers_count = 0 

for row in movies_table:
    if 'триллер' in row[3]:
        thrillers_count += 1

print(thrillers_count)

3

**Вопросы по 20 заданию**

**Задание 21**

Посчитайте фильмы, которые вышли после 1990 года. Результат сохраните в переменную after_ninety_count.

In [123]:
movies_table = [
    ['Побег из Шоушенка', 'США', 1994, 'драма', 142, 9.111],
    ['Крёстный отец', 'США', 1972, 'драма, криминал', 175, 8.730],
    ['Тёмный рыцарь', 'США', 2008, 'фантастика, боевик, триллер', 152, 8.499],
    ['Список Шиндлера', 'США', 1993, 'драма', 195, 8.818],
    ['Властелин колец: Возвращение Короля', 'Новая Зеландия', 2003, 'фэнтези, приключения, драма', 201, 8.625],
    ['Криминальное чтиво', 'США', 1994, 'триллер, комедия, криминал', 154, 8.619],
    ['Хороший, плохой, злой', 'Италия', 1966, 'вестерн', 178, 8.521],
    ['Бойцовский клуб', 'США', 1999, 'триллер, драма, криминал', 139, 8.644],
    ['Харакири', 'Япония', 1962, 'драма, боевик, история', 133, 8.106],
    ['Сталкер', 'СССР', 1979, 'фантастика, драма, детектив', 163, 8.083],
    ['Иди и смотри', 'СССР', 1985, 'драма, военный', 136, 8.094]
]

after_ninety_count = 0

for row in movies_table:
    if row[2] > 1990:
        after_ninety_count += 1

print(after_ninety_count)

6

**Вопросы по 21 заданию**